import {getCrmSupabaseClient} from './crm-supabase.js';
import {loadModerationDetail,loadModerationInbox,manageVisualAnalysisPlan,moderatePublication,requestMagicLink,requireAdminSession} from './crm-service.js';

const client=getCrmSupabaseClient(),authScreen=document.querySelector('#auth-screen'),app=document.querySelector('#crm-app'),authStatus=document.querySelector('#auth-status'),crmStatus=document.querySelector('#crm-status'),inboxBody=document.querySelector('#inbox-body'),detailPanel=document.querySelector('#publication-detail'),filters=document.querySelector('#filters');
let selectedPublicationId=null,privateMap=null,privateMarker=null;
const correctionFields={contacto_nombre:'Nombre de contacto',contacto_email:'Correo de contacto',contacto_telefono:'Teléfono',contacto_organizacion:'Corredora',titulo_publico:'Título',descripcion_publica:'Descripción',precio_publicacion:'Precio',superficie_m2:'Superficie',region:'Región',comuna:'Comuna',sector:'Sector',rol:'Rol',agua:'Agua',luz:'Luz',acceso:'Acceso',topografia:'Topografía',ciudad_principal:'Ciudad cercana',distancia_ciudad:'Distancia',facilidad_pago:'Facilidad de pago',detalle_facilidad_pago:'Detalle de pago'};

function text(container,tag,value,className){const node=document.createElement(tag);node.textContent=value??'';if(className)node.className=className;container.append(node);return node;}
function setStatus(node,message='',error=false){node.textContent=message;node.classList.toggle('is-error',error);}
function formatDate(value){return value?new Date(value).toLocaleString('es-CL'):'—';}
function stateLabel(value){return {pendiente_revision:'Pendiente',requiere_cambios:'Requiere corrección',aprobada:'Aprobada',rechazada:'Rechazada'}[value]||value;}
function fact(container,label,value){const item=document.createElement('div');item.className='fact';text(item,'span',label);text(item,'strong',value==null||value===''?'—':String(value));container.append(item);}

async function authenticate(){
 if(!client){setStatus(authStatus,'La configuración pública de Supabase no está disponible.',true);return;}
 try{const profile=await requireAdminSession(client);if(!profile){authScreen.hidden=false;app.hidden=true;return;}authScreen.hidden=true;app.hidden=false;document.querySelector('#admin-identity').textContent=`${profile.nombre} · Perfil administrador activo`;await refreshInbox();}catch{await client.auth.signOut();authScreen.hidden=false;app.hidden=true;setStatus(authStatus,'Tu sesión no corresponde a un administrador activo.',true);}
}

function currentFilters(){const data=new FormData(filters);return Object.fromEntries([...data.entries()].map(([key,value])=>[key,String(value).trim()]));}
async function refreshInbox(){
 setStatus(crmStatus,'Actualizando bandeja…');
 try{const {counts,items}=await loadModerationInbox(client,currentFilters());document.querySelector('#count-pending').textContent=counts.pendientes||0;document.querySelector('#count-changes').textContent=counts.requieren_correccion||0;document.querySelector('#count-approved').textContent=counts.aprobadas||0;document.querySelector('#count-rejected').textContent=counts.rechazadas||0;renderInbox(items);setStatus(crmStatus,`${items.length} publicación(es) en la bandeja.`);}catch{setStatus(crmStatus,'No fue posible cargar la bandeja. Comprueba tu sesión administrativa.',true);}
}
function renderInbox(items){inboxBody.replaceChildren();if(!items.length){const row=document.createElement('tr'),cell=document.createElement('td');cell.colSpan=7;cell.textContent='No hay publicaciones con estos filtros.';row.append(cell);inboxBody.append(row);return;}items.forEach(item=>{const row=document.createElement('tr');const code=document.createElement('td'),button=text(code,'button',item.codigo_publico,'row-button');button.type='button';button.addEventListener('click',()=>openDetail(item.id));row.append(code);[item.corredor,item.propiedad,item.comuna,formatDate(item.creado_en),item.plan||'—'].forEach(value=>text(row,'td',value));const status=document.createElement('td');text(status,'span',stateLabel(item.estado),'state');row.append(status);inboxBody.append(row);});}

async function openDetail(id){selectedPublicationId=id;detailPanel.replaceChildren();text(detailPanel,'p','Cargando información privada…');try{renderDetail(await loadModerationDetail(client,id));}catch{detailPanel.replaceChildren();text(detailPanel,'p','No fue posible cargar el detalle o generar los enlaces temporales de las fotografías.','private-note');}}
function renderDetail(detail){
 const p=detail.publicacion;detailPanel.replaceChildren();const heading=document.createElement('div');heading.className='detail-heading';const title=document.createElement('div');text(title,'span',p.codigo_publico,'eyebrow');text(title,'h2',p.titulo_publico);heading.append(title);text(heading,'span',stateLabel(p.estado),'state');detailPanel.append(heading);
 const contact=section('Publicador y contacto'),contactGrid=grid();fact(contactGrid,'Tipo',p.tipo_publicador);fact(contactGrid,'Nombre',p.contacto_nombre);fact(contactGrid,'Organización',p.contacto_organizacion);fact(contactGrid,'Correo',p.contacto_email);fact(contactGrid,'Teléfono',p.contacto_telefono);fact(contactGrid,'Plan contratado',p.plan_contratado||p.plan_seleccionado);contact.append(contactGrid);
 const formData=p.datos_formulario||{},propertyData=formData.propiedad||{},houseData=formData.casa||{},rawForm=formData.formulario||{},propertyType=String(formData.tipo||propertyData.tipo||rawForm.tipo||'parcela').toLowerCase();
 const property=section(propertyType==='casa'?'Casa publicada':'Parcela o campo'),propertyGrid=grid();
 const commonFacts=[['Tipo de inmueble',propertyType==='casa'?'Casa':'Parcela/Campo'],['Descripción',p.descripcion_publica],['Superficie',p.superficie_m2?`${p.superficie_m2} m²`:null],['Precio',p.precio_publicacion?`$${Number(p.precio_publicacion).toLocaleString('es-CL')}`:null],['Región',p.region],['Comuna',p.comuna],['Sector',p.sector]];
 const specificFacts=propertyType==='casa'?[['Superficie construida',propertyData.superficieConstruida||rawForm.casaSuperficie],['Superficie de terreno',propertyData.superficieTerreno||rawForm.casaTerreno],['Dormitorios',houseData.habitaciones||rawForm.habitaciones],['Baños',houseData.banos||rawForm.banos],['Pisos',houseData.pisos||rawForm.pisos],['Material',houseData.material||rawForm.material],['Estado',houseData.estado||rawForm.estadoCasa],['Estacionamientos',houseData.estacionamientos||rawForm.estacionamientos],['Calefacción',houseData.calefaccion||rawForm.calefaccion]]:[['Rol',p.rol],['Agua',p.agua],['Luz',p.luz],['Acceso',p.acceso],['Topografía',p.topografia],['Facilidad de pago',p.facilidad_pago==null?null:(p.facilidad_pago?'Sí':'No')]];
 [...commonFacts,...specificFacts].forEach(([label,value])=>fact(propertyGrid,label,value));property.append(propertyGrid);
 const photos=section('Fotografías privadas'),gallery=document.createElement('div');gallery.className='photos';detail.fotos.forEach((photo,index)=>{const figure=document.createElement('figure');if(photo.es_portada)figure.className='cover';const image=document.createElement('img');image.src=photo.signedUrl;image.alt=`Fotografía privada ${index+1}`;image.loading='lazy';figure.append(image);text(figure,'figcaption',photo.es_portada?`Portada · ${index+1}`:`Foto ${index+1}`);gallery.append(figure);});photos.append(gallery);text(photos,'p','Los enlaces expiran en 5 minutos.','private-note');
 const location=section('Ubicación privada');fact(location,'Referencia pública',p.ubicacion_publica_aproximada);if(p.latitud_privada!=null&&p.longitud_privada!=null){const map=document.createElement('div');map.id='private-location-map';map.className='private-map';location.append(map);text(location,'p','Coordenadas exactas visibles solo en esta sesión administrativa.','private-note');requestAnimationFrame(()=>renderPrivateMap(Number(p.latitud_privada),Number(p.longitud_privada)));}else text(location,'p','La publicación no contiene coordenadas exactas.');
 const consent=section('Consentimientos y análisis');const consentGrid=grid(),planIa=detail.planIa||{};fact(consentGrid,'GPS/EXIF',formData.autorizaGpsFotos?'Autorizado':'No autorizado');fact(consentGrid,'Análisis visual',p.analisis_ia_consentimiento?'Autorizado':'No autorizado');fact(consentGrid,'Plan solicitado',planIa.plan_solicitado||p.plan_seleccionado);fact(consentGrid,'Entitlement IA',planIa.entitlement_activo?'Activo':planIa.entitlement_estado||'No emitido');consent.append(consentGrid);if(planIa.elegible)consent.append(planManagementActions(planIa));if(detail.analisis_visual&&['gold','platinum'].includes(p.plan_contratado||p.plan_seleccionado)){const ai=text(consent,'div',JSON.stringify(detail.analisis_visual.sugerencias||{},null,2),'ai-box');ai.setAttribute('aria-label','Resultado del análisis visual');}
 const history=section('Historial inmutable'),historyList=document.createElement('div');historyList.className='history';(detail.moderacion||[]).forEach(record=>{const item=document.createElement('article');text(item,'strong',`${stateLabel(record.estado_anterior)} → ${stateLabel(record.estado_nuevo)}`);text(item,'p',record.motivo||record.accion);text(item,'small',formatDate(record.creado_en));historyList.append(item);});(detail.versiones||[]).forEach(version=>{const item=document.createElement('article');text(item,'strong',`Versión ${version.version}`);text(item,'p',version.origen);text(item,'small',formatDate(version.creado_en));historyList.append(item);});if(!historyList.childNodes.length)text(historyList,'p','Sin decisiones previas.');history.append(historyList);
 detailPanel.append(contact,property,photos,location,consent,history,moderationActions(p));
}
function section(title){const node=document.createElement('section');node.className='detail-section';text(node,'h3',title);return node;}function grid(){const node=document.createElement('div');node.className='fact-grid';return node;}
function renderPrivateMap(lat,lng){if(!globalThis.L)return;const target=document.querySelector('#private-location-map');if(!target)return;if(privateMap){privateMap.remove();privateMap=null;}privateMap=L.map(target).setView([lat,lng],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(privateMap);privateMarker=L.marker([lat,lng]).addTo(privateMap).bindPopup('Ubicación privada').openPopup();}
function moderationActions(p){const box=document.createElement('div');box.className='moderation-actions';if(p.estado==='pendiente_revision'){box.append(actionButton('Aprobar','primary',approve),actionButton('Solicitar correcciones','secondary',()=>openDialog('correction-dialog')),actionButton('Rechazar definitivamente','danger',()=>openDialog('reject-dialog')));}if(p.estado==='requiere_cambios')box.append(actionButton('Rechazar definitivamente','danger',()=>openDialog('reject-dialog')));if(p.estado==='rechazada')box.append(actionButton('Revertir rechazo','secondary',reverseRejection));return box;}
function planManagementActions(planIa){const box=document.createElement('div');box.className='moderation-actions ai-plan-actions';if(planIa.entitlement_activo)box.append(actionButton('Revocar activación de IA','danger',()=>managePlanIa('revocar')));else box.append(actionButton('Confirmar contratación y activar IA','primary',()=>managePlanIa('confirmar')));return box;}
function actionButton(label,className,handler){const button=document.createElement('button');button.type='button';button.className=className;button.textContent=label;button.addEventListener('click',handler);return button;}
async function approve(){if(!confirm('Confirma que revisaste los datos y deseas aprobar esta publicación.'))return;await runDecision({publicationId:selectedPublicationId,action:'aprobar',confirm:true},'Publicación aprobada y preparada para el catálogo.');}
async function reverseRejection(){if(!confirm('Esta acción devolverá la publicación a revisión. ¿Continuar?'))return;const reason=prompt('Indica el motivo administrativo de la reversión:');if(!reason?.trim())return;await runDecision({publicationId:selectedPublicationId,action:'revertir_rechazo',reason,confirm:true},'Rechazo revertido; la publicación volvió a revisión.');}
async function runDecision(payload,success){setStatus(crmStatus,'Registrando decisión…');try{const result=await moderatePublication(client,payload);setStatus(crmStatus,success);await refreshInbox();await openDetail(payload.publicationId);return result;}catch{setStatus(crmStatus,'La decisión fue rechazada por las reglas de seguridad o por el estado actual.',true);return null;}}
async function managePlanIa(action){const verb=action==='confirmar'?'activar':'revocar',reason=prompt(`Indica el motivo administrativo para ${verb} la IA:`);if(!reason?.trim())return;if(!confirm(`Confirma que deseas ${verb} el entitlement de IA para esta publicación.`))return;setStatus(crmStatus,action==='confirmar'?'Confirmando contratación…':'Revocando entitlement…');try{await manageVisualAnalysisPlan(client,{publicationId:selectedPublicationId,action,reason});setStatus(crmStatus,action==='confirmar'?'Plan confirmado y entitlement activo. No se realizó ninguna llamada a OpenAI.':'Entitlement revocado y registrado en auditoría.');await openDetail(selectedPublicationId);}catch{setStatus(crmStatus,'La acción de IA fue rechazada. Solo Gold o Platinum pueden recibir entitlement y tu perfil debe estar activo.',true);}}
function openDialog(id){const dialog=document.querySelector(`#${id}`);dialog.querySelector('form')?.reset();dialog.showModal();dialog.querySelector('textarea,select,input')?.focus();}

document.querySelector('#auth-form').addEventListener('submit',async event=>{event.preventDefault();setStatus(authStatus,'Enviando enlace seguro…');try{await requestMagicLink(client,document.querySelector('#admin-email').value,`${location.origin}${location.pathname}`);setStatus(authStatus,'Revisa tu correo. El enlace solo dará acceso si tu perfil administrador está activo.');}catch{setStatus(authStatus,'No fue posible solicitar el enlace. Verifica el correo y la configuración de Auth.',true);}});
document.querySelector('#logout').addEventListener('click',async()=>{await client.auth.signOut();location.reload();});filters.addEventListener('submit',event=>{event.preventDefault();void refreshInbox();});filters.addEventListener('reset',()=>requestAnimationFrame(refreshInbox));document.querySelectorAll('.metrics button').forEach(button=>button.addEventListener('click',()=>{filters.elements.estado.value=button.dataset.state;void refreshInbox();}));
document.querySelectorAll('dialog [data-close]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));
const fieldsBox=document.querySelector('#correction-fields');Object.entries(correctionFields).forEach(([value,label])=>{const option=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.name='fields';input.value=value;option.append(input,document.createTextNode(label));fieldsBox.append(option);});
document.querySelector('#correction-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),fields=data.getAll('fields'),status=form.querySelector('[data-status]');if(!fields.length){setStatus(status,'Selecciona al menos un campo.',true);return;}setStatus(status,'Generando acceso de un solo uso…');const result=await runDecision({publicationId:selectedPublicationId,action:'solicitar_correcciones',reason:data.get('reason'),fields,message:data.get('message')},'Correcciones solicitadas y registradas.');if(!result?.correction_token){setStatus(status,'No fue posible generar el acceso.',true);return;}form.closest('dialog').close();const link=`${location.origin}/plataforma/corregir-publicacion/#token=${encodeURIComponent(result.correction_token)}`;document.querySelector('#correction-link').value=link;document.querySelector('#correction-link-dialog').showModal();});
document.querySelector('#reject-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),status=form.querySelector('[data-status]');if(prompt('Para confirmar el rechazo definitivo, escribe RECHAZAR:')!=='RECHAZAR'){setStatus(status,'Confirmación cancelada.',true);return;}const result=await runDecision({publicationId:selectedPublicationId,action:'rechazar',reason:data.get('reason'),category:data.get('category'),message:data.get('message'),confirm:true},'Publicación rechazada y conservada fuera del catálogo.');if(result)form.closest('dialog').close();});
document.querySelector('#copy-correction-link').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.querySelector('#correction-link').value);setStatus(document.querySelector('#copy-status'),'Enlace copiado. No lo publiques ni lo registres en sistemas de analítica.');}catch{setStatus(document.querySelector('#copy-status'),'No pudimos copiarlo automáticamente. Selecciona el enlace y cópialo manualmente.',true);}});

client?.auth.onAuthStateChange(()=>setTimeout(authenticate,0));void authenticate();
