export const CURRENT_SCHEMA_VERSION=10;
export const CURRENT_STORAGE_KEY='tpl_publicar_parcela_draft_v10';
export const PREVIOUS_STORAGE_KEY='tpl_publicar_parcela_draft_v9';
export function normalizePublisherType(value){const text=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return text.includes('corredor')||text.includes('empresa')||text.includes('inmobiliaria')?'corredor':text?'dueno':'';}
const list=value=>Array.isArray(value)?value:value?[value]:[];
export function migrateDraft(draft){
 if(!draft||typeof draft!=='object')return null;if(Number(draft.schemaVersion)===CURRENT_SCHEMA_VERSION)return {...draft};
 const origin=draft.descripcion_origen||draft.descripcionOriginal||draft.relato||draft.voice?.transcripcion||draft.voz?.transcripcion||'';const published=draft.descripcion_publica||draft.descripcionPublica||draft.descripcionOptimizada||'';
 return {schemaVersion:CURRENT_SCHEMA_VERSION,migratedFrom:Number(draft.schemaVersion)||9,migrationStatus:'compatible-v10',savedAt:new Date().toISOString(),descripcion_origen:origin,descripcion_publica:published,titulo_publico:draft.titulo_publico||draft.tituloPublico||'',descripcion_publica_editada:Boolean(draft.descripcion_publica_editada),titulo_publico_editado:Boolean(draft.titulo_publico_editado),ultima_descripcion_generada:draft.ultima_descripcion_generada||'',ultimo_titulo_generado:draft.ultimo_titulo_generado||'',
  region:draft.region||'',comuna:draft.comuna||'',sector:draft.sector||'',superficie:draft.superficie||'',precio:draft.precio||'',rol:draft.rol||'',agua:draft.agua||'',luz:draft.luz||'',acceso:draft.acceso||'',topografia:draft.topografia||'',naturaleza:list(draft.naturaleza),cuerposAgua:list(draft.cuerposAgua||draft.aguaNatural),servicios:list(draft.servicios||draft.serviciosCercanos),ciudadPrincipal:draft.ciudadPrincipal||'',distanciaCiudad:draft.distanciaCiudad||draft.distancia||'',facilidadPago:draft.facilidadPago||'',detalleFacilidad:draft.detalleFacilidad||'',
  tipoPublicador:normalizePublisherType(draft.tipoPublicador),nombreDueno:draft.nombreDueno||draft.nombre||'',correoDueno:draft.correoDueno||draft.correo||'',telefonoDueno:draft.telefonoDueno||draft.telefono||'',corredoraNombre:draft.corredoraNombre||'',representanteNombre:draft.representanteNombre||draft.nombre||'',correoCorredor:draft.correoCorredor||draft.correo||'',telefonoCorredor:draft.telefonoCorredor||draft.telefono||'',whatsappCorredor:draft.whatsappCorredor||'',anosExperiencia:draft.anosExperiencia||'',rutCorredor:draft.rutCorredor||'',sitioWeb:draft.sitioWeb||'',redSocial:draft.redSocial||'',presentacionCorredor:draft.presentacionCorredor||'',logoCorredorMeta:draft.logoCorredorMeta||null,
  montoLiquido:draft.montoLiquido||'',aceptaPartner:Boolean(draft.aceptaPartner),planCorredor:draft.planCorredor==='inicial'?'inicio':draft.planCorredor||draft.commercial?.plan||'',qualityAcceptance:draft.qualityAcceptance||{accepted:false,version:'tpl-broker-quality-v1',acceptedAt:null},changedFromOwnerToBroker:Boolean(draft.changedFromOwnerToBroker),selectedEstimate:draft.selectedEstimate||'',analysisData:draft.analysisData||null,photos:Array.isArray(draft.photos)?draft.photos:[],informacionComplementaria:draft.informacionComplementaria||'',enrichmentData:draft.enrichmentData||null,responsable_tipo:draft.responsable_tipo||'',responsable_id:draft.responsable_id||'',responsable_nombre:draft.responsable_nombre||'',responsable_whatsapp:draft.responsable_whatsapp||'',responsable_email:draft.responsable_email||'',solicitudes_visita:Array.isArray(draft.solicitudes_visita)?draft.solicitudes_visita:[],estado:draft.estado||draft.submission?.status||'',fecha_envio:draft.fecha_envio||draft.submission?.submittedAt||'',correo_contacto:draft.correo_contacto||draft.submission?.contactEmail||'',codigo_temporal:draft.codigo_temporal||draft.submission?.temporaryCode||'',tipo_publicador:draft.tipo_publicador||draft.submission?.publisherType||'',plan_modelo_comercial:draft.plan_modelo_comercial||draft.submission?.commercialModel||'',enviado:Boolean(draft.enviado||draft.submission?.status==='pendiente_revision'),submission:draft.submission||null};
}

