import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {analyzeParcelText,cleanVoiceTranscript,extractSurface} from './analyzer.js';import {BROKER_PLANS,PLAN_COMPARISON,resolvedPlanBenefits} from './plans-config.js';import {CHILE_LOCATIONS,communesForRegion,regionForCommune} from './chile-locations.js';import {generateCommercialContent,generatePublicTitle,shouldConfirmDescriptionRegeneration} from './content-generator.js';import {enrichmentProvider,ENRICHMENT_STATUS} from './enrichment-service.js';import {estimateParcel} from './estimator.js';import {CURRENT_SCHEMA_VERSION,migrateDraft} from './draft.js';import {getVoiceView} from './voice-state.js';
import {QUALITY_COMMITMENT,USER_RATING_CATEGORIES,TPL_EVALUATION_LEVELS,TPL_EVALUATION_FACTORS,RESPONSE_TIME_CATEGORIES,MODERATION_STATES,MODERATION_SUBJECTS,MODERATION_RECORD_FIELDS,simulatedReputation,createQualityAcceptance} from './reputation-config.js';
import {buildPreviewBadges,buildResponsible,buildWhatsappMessage,createVisitRequest,whatsappUrl} from './preview-model.js';
import {contactEmailFor,generateTemporaryCode,prepareLocalSubmission} from './submission-service.js';
import {MAX_PHOTOS,MAX_FINAL_TOTAL_PHOTO_BYTES,formatPhotoUsage,validateOriginalPhoto} from './photo-optimizer.js';
import {hasPrivateCoordinates,isValidGoogleMapsLink,locationIsMissing,shouldShowLocationWarning} from './photo-geolocation.js';
import {approximateCoordinateLabel,coordinatesToGoogleMapsLink} from './location-picker.js';

assert.equal(cleanVoiceTranscript('tiene tiene rol y y bosque nativo bosque nativo'),'tiene rol y bosque nativo');assert.equal(cleanVoiceTranscript('muy muy buena vista'),'muy muy buena vista');assert.equal(extractSurface('cinco mil metros'),5000);assert.equal(extractSurface('media hectárea'),5000);
const detected=analyzeParcelText('Parcela en Florida, sector Copiulemu, de cinco mil metros. Precio $20.000.000, tiene rol, agua de pozo, luz en el camino, camino de ripio, lomaje suave, bosque nativo, río, a 20 km de Concepción y acepto cuotas.');assert.equal(detected.region,'Biobío');assert.equal(detected.comuna,'Florida');assert.equal(detected.superficie,5000);assert.equal(detected.precio,20000000);
assert.equal(CHILE_LOCATIONS.length,16);assert.ok(CHILE_LOCATIONS.reduce((sum,item)=>sum+item.communes.length,0)>=345);assert.ok(communesForRegion('Biobío').includes('Florida'));assert.equal(regionForCommune('Pucón'),'La Araucanía');

assert.deepEqual(BROKER_PLANS.map(plan=>plan.id),['inicio','profesional','gold','platinum']);assert.deepEqual(BROKER_PLANS.map(plan=>plan.price),[0,47000,78900,120000]);assert.deepEqual(BROKER_PLANS.map(plan=>plan.limit),[1,5,10,20]);assert.deepEqual(BROKER_PLANS.map(plan=>plan.priceLabel),['Gratis','$47.000','$78.900','$120.000']);assert.deepEqual(BROKER_PLANS.map(plan=>plan.cta),['Comenzar gratis','Elegir Profesional','Elegir Gold','Elegir Platinum']);assert.match(BROKER_PLANS[1].badge,/Más elegido/);assert.match(BROKER_PLANS[3].badge,/Mayor capacidad/);assert.ok(resolvedPlanBenefits('platinum').length>resolvedPlanBenefits('gold').length);assert.equal(PLAN_COMPARISON.length,12);assert.ok(PLAN_COMPARISON.every(row=>row.length===5));for(const plan of BROKER_PLANS)assert.equal(migrateDraft({schemaVersion:8,planCorredor:plan.id}).planCorredor,plan.id);
assert.equal(QUALITY_COMMITMENT.version,'tpl-broker-quality-v1');assert.equal(USER_RATING_CATEGORIES.length,5);assert.deepEqual(TPL_EVALUATION_LEVELS.map(item=>item.label),['En evaluación','Verificado TPL','Destacado TPL','Excelencia TPL']);assert.equal(TPL_EVALUATION_FACTORS.length,6);assert.deepEqual(RESPONSE_TIME_CATEGORIES.map(item=>item.label),['Menos de 1 hora','Durante el mismo día','En 24 horas','Sin información suficiente']);assert.deepEqual(MODERATION_STATES,['activo','advertido','requiere_correccion','pausado','suspendido','retirado']);assert.deepEqual(MODERATION_SUBJECTS,['corredor','publicacion']);assert.deepEqual(MODERATION_RECORD_FIELDS,['motivo','fecha','responsable','evidencia','revision_apelacion']);assert.deepEqual(createQualityAcceptance(true,'2026-07-13T10:00:00.000Z'),{accepted:true,version:'tpl-broker-quality-v1',acceptedAt:'2026-07-13T10:00:00.000Z'});assert.deepEqual(createQualityAcceptance(false,'2026-07-13T10:00:00.000Z'),{accepted:false,version:'tpl-broker-quality-v1',acceptedAt:null});const reputationA=simulatedReputation(),reputationB=simulatedReputation();reputationA.globalScore=1;assert.equal(reputationB.globalScore,4.7);assert.equal(reputationB.comments.length,2);assert.ok(reputationB.comments.every(comment=>comment.author&&comment.date&&comment.score&&comment.comment&&comment.interactionType&&comment.moderationStatus));

const privateStory='Eh, esta es una parcela súper linda, linda, llámenme pronto.';const confirmed={relato:privateStory,region:'Biobío',comuna:'Florida',sector:'Copiulemu',superficie:5000,rol:'Rol propio',agua:'Pozo',luz:'Cercana',acceso:'Ripio',topografia:'Plana',naturaleza:['Bosque nativo'],cuerposAgua:['Estero'],servicios:['Comercio'],ciudadPrincipal:'Concepción',distanciaCiudad:'20 km',facilidadPago:'si'};const content=generateCommercialContent(confirmed);assert.match(content.titulo_publico,/5\.000 m²/);assert.match(content.titulo_publico,/Florida/);assert.ok(content.titulo_publico.length<=70);assert.doesNotMatch(content.titulo_publico,/Hermosa parcela/i);assert.match(content.descripcion_publica,/agua: Pozo/i);assert.match(content.descripcion_publica,/acceso: Ripio/i);assert.doesNotMatch(content.descripcion_publica,/llámenme|súper linda/i);assert.equal(privateStory,'Eh, esta es una parcela súper linda, linda, llámenme pronto.');assert.equal(shouldConfirmDescriptionRegeneration({modified:true,current:'Edición manual',lastGenerated:'Automática'}),true);assert.equal(shouldConfirmDescriptionRegeneration({modified:false,current:'Automática',lastGenerated:'Automática'}),false);
const enrichment=await enrichmentProvider.suggest(confirmed);assert.equal(enrichment.status,ENRICHMENT_STATUS.SUGGESTED);assert.equal(enrichment.provider,'mock-local-v1');assert.deepEqual(enrichment.sources,[]);assert.equal(enrichment.confidence,'baja');
const estimate=estimateParcel({...confirmed,price:18000000});assert.equal(estimate.scenarios.length,3);assert.match(estimate.disclaimer,/no corresponde a una tasación bancaria/);

const migratedOwner=migrateDraft({schemaVersion:6,tipoPublicador:'dueno',descripcion_origen:'Origen privado',descripcion_publica:'Pública',tituloPublico:'Título anterior',nombre:'Ana',correo:'ana@example.cl',telefono:'+56911111111',montoLiquido:18000000,photos:[{name:'uno.jpg'}]});assert.equal(migratedOwner.schemaVersion,10);assert.equal(migratedOwner.migratedFrom,6);assert.equal(migratedOwner.descripcion_origen,'Origen privado');assert.equal(migratedOwner.descripcion_publica,'Pública');assert.equal(migratedOwner.titulo_publico,'Título anterior');assert.equal(migratedOwner.nombreDueno,'Ana');assert.deepEqual(migratedOwner.photos,[{name:'uno.jpg'}]);
const migratedBroker=migrateDraft({schemaVersion:7,tipoPublicador:'corredor',representanteNombre:'Luis',correoCorredor:'luis@example.cl',telefonoCorredor:'+56922222222',planCorredor:'inicio'});assert.equal(migratedBroker.representanteNombre,'Luis');assert.equal(migratedBroker.correoCorredor,'luis@example.cl');assert.equal(migratedBroker.planCorredor,'inicio');assert.equal(migratedBroker.qualityAcceptance.accepted,false);assert.equal(migratedBroker.qualityAcceptance.version,'tpl-broker-quality-v1');assert.equal(CURRENT_SCHEMA_VERSION,10);assert.deepEqual(migratedBroker.solicitudes_visita,[]);

const badges=buildPreviewBadges({comuna:'Florida',superficie:5000,rol:'propio',luz:'conectada',facilidadPago:'si',ciudadPrincipal:'Concepción'});assert.deepEqual(badges,['Florida','5.000 m²','Con rol','Facilidad de pago']);assert.equal(badges.length,4);assert.equal(buildPreviewBadges({comuna:'Florida',superficie:5000,naturaleza:['Bosque nativo'],ciudadPrincipal:'Concepción'}).length,4);
const ownerResponsible=buildResponsible('dueno',{nombreDueno:'Nombre privado',telefonoDueno:'+56911111111'});assert.equal(ownerResponsible.responsable_tipo,'asesor_tpl');assert.equal(ownerResponsible.responsable_nombre,'Asesor Tu Parcela Lista');assert.notEqual(ownerResponsible.responsable_whatsapp,'+56911111111');const brokerResponsible=buildResponsible('corredor',{corredoraNombre:'Corredora Sur',representanteNombre:'Luis',whatsappCorredor:'+56922222222',correoCorredor:'luis@example.cl'});assert.equal(brokerResponsible.responsable_tipo,'corredor');assert.equal(brokerResponsible.responsable_nombre,'Corredora Sur');assert.equal(brokerResponsible.responsable_whatsapp,'+56922222222');assert.match(buildWhatsappMessage('Parcela en Florida'),/"Parcela en Florida"/);assert.match(whatsappUrl('+56922222222','Parcela en Florida'),/^https:\/\/wa\.me\/56922222222\?text=/);const visit=createVisitRequest({nombre:'María',telefono:'+56933333333',correo:'maria@example.cl',fechaPreferida:'2026-07-20',horario:'Tarde'},brokerResponsible,{id:'visit-test',createdAt:'2026-07-13T12:00:00.000Z'});assert.equal(visit.responsable_tipo,'corredor');assert.equal(visit.responsable_id,'broker-local');assert.equal(visit.estado,'simulada_local');
const submissionDate=new Date('2026-07-13T12:00:00.000Z');assert.equal(generateTemporaryCode({date:submissionDate,random:()=>.000123}),'TPL-PUB-2026-000123');assert.equal(contactEmailFor({tipoPublicador:'dueno',correoDueno:'dueno@example.cl'}),'dueno@example.cl');assert.equal(contactEmailFor({tipoPublicador:'corredor',correoCorredor:'corredor@example.cl'}),'corredor@example.cl');const ownerSubmission=prepareLocalSubmission({schemaVersion:10,idempotencyKey:'11111111-1111-4111-8111-111111111111',tipoPublicador:'dueno',correoDueno:'dueno@example.cl',titulo_publico:'Parcela en Florida',descripcion_publica:'Descripción pública',commercial:{type:'partner'}},{date:submissionDate,random:()=>.000123});assert.equal(ownerSubmission.estado,'preparando_envio');assert.equal(ownerSubmission.enviado,false);assert.equal(ownerSubmission.codigo_temporal,'TPL-PUB-2026-000123');assert.equal(ownerSubmission.plan_modelo_comercial,'partner');assert.equal(ownerSubmission.submission.transport,'supabase-edge-v1');const repeatedSubmission=prepareLocalSubmission(ownerSubmission,{date:new Date('2027-01-01T00:00:00.000Z'),random:()=>.999999});assert.equal(repeatedSubmission.codigo_temporal,ownerSubmission.codigo_temporal);assert.equal(repeatedSubmission.submission.idempotencyKey,ownerSubmission.submission.idempotencyKey);const brokerSubmission=prepareLocalSubmission({idempotencyKey:'22222222-2222-4222-8222-222222222222',tipoPublicador:'corredor',correoCorredor:'corredor@example.cl',planCorredor:'gold',titulo_publico:'Parcela corredor',descripcion_publica:'Descripción corredor'},{date:submissionDate,random:()=>.5});assert.equal(brokerSubmission.plan_modelo_comercial,'gold');assert.equal(brokerSubmission.correo_contacto,'corredor@example.cl');

assert.equal(getVoiceView('initial',false).label,'Comenzar');assert.equal(getVoiceView('listening',false).label,'Escuchando…');assert.equal(getVoiceView('paused',true).label,'Continuar');
const html=await readFile(new URL('./index.html',import.meta.url),'utf8'),script=await readFile(new URL('./publicar-parcela.js',import.meta.url),'utf8'),css=await readFile(new URL('./publicar-parcela.css',import.meta.url),'utf8');assert.equal((html.match(/data-step="[1-6]"/g)||[]).length,6);assert.equal((html.match(/data-step="loading"/g)||[]).length,1);assert.match(html,/Paso 1 de 6/);assert.match(html,/<b>Descripción<\/b>/);assert.match(html,/<b>Fotos<\/b>/);assert.match(html,/data-step="5"[\s\S]{0,900}publicar-parcela-fotografo-campo-v2\.png/);assert.match(html,/data-step="1"[\s\S]{0,4500}name="relato"/);assert.match(script,/Math\.min\(6,step\)/);assert.match(script,/step===5&&!photos\.length/);assert.match(script,/change-cover'\)\.addEventListener\('click',\(\)=>showStep\(5\)/);assert.match(css,/publication-success/);
assert.equal(MAX_PHOTOS,12);assert.equal(MAX_FINAL_TOTAL_PHOTO_BYTES,20*1024*1024);assert.match(formatPhotoUsage(2,1024*1024),/2 de 12 fotografías/);assert.throws(()=>validateOriginalPhoto(new Blob(['x'],{type:'text/plain'})),/formato no compatible/);
const coordinates={latitude:-36.82,longitude:-73.05};assert.equal(hasPrivateCoordinates(coordinates),true);assert.equal(locationIsMissing({}),true);assert.equal(isValidGoogleMapsLink(coordinatesToGoogleMapsLink(coordinates)),true);assert.equal(shouldShowLocationWarning({evaluationReady:true}),true);assert.match(approximateCoordinateLabel(coordinates),/-36\.820, -73\.050/);
console.log('OK: flujo de 6 etapas, descripción inicial, fotos al final, módulos comerciales, ubicación y envío Supabase.');
