(() => {
  const KEY='tpl_landing_engine_v1';
  const params=new URLSearchParams(location.search);
  const pathSlug=location.pathname.split('/').filter(Boolean).at(-1);
  const id=params.get('id')||(pathSlug&&pathSlug!=='landing'?pathSlug:'land-caburgua');
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let items=[];try{items=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{}
  const stored=items.find(x=>x.id===id||x.slug===id);
  const published=window.TPL_getPublicLanding?.(id);
  const l=stored||published;
  const root=document.getElementById('landing-root');
  if(!l){root.innerHTML='<section class="missing"><h1>Landing no disponible</h1><p>Comprueba el enlace o vuelve a Tu Parcela Lista.</p><a class="primary" href="/">Volver al inicio</a></section>';return;}
  document.title=l.seoTitle||l.title||'Landing Premium';
  const wa=l.whatsapp?`https://wa.me/${String(l.whatsapp).replace(/\D/g,'')}?text=${encodeURIComponent('Hola, quiero información sobre '+l.title)}`:'#contacto';
  root.innerHTML=`<header class="top"><a href="/" class="brand">TU PARCELA LISTA</a><nav><a href="#beneficios">Beneficios</a><a href="#galeria">Galería</a><a href="#contacto" class="nav-cta">${esc(l.ctaPrimary||'Agendar visita')}</a></nav></header><section class="hero" style="--hero:url('${esc(l.heroImage)}')"><div class="overlay"></div><div class="hero-content"><span>${esc(l.eyebrow||'PROYECTO PREMIUM')}</span><h1>${esc(l.title)}</h1><p>${esc(l.subtitle)}</p><div class="hero-meta"><strong>${esc(l.price)}</strong><span>${esc(l.location)}</span></div><div class="hero-actions"><a href="#contacto" class="primary">${esc(l.ctaPrimary||'Agendar visita')}</a><a href="${wa}" class="secondary">${esc(l.ctaSecondary||'WhatsApp')}</a></div></div></section><section id="beneficios" class="section intro"><div><span class="kicker">UNA OPORTUNIDAD ÚNICA</span><h2>Un lugar para vivir, invertir y disfrutar</h2></div><p>${esc(l.description)}</p></section><section class="benefits">${(l.benefits||[]).map((b,i)=>`<article><span>0${i+1}</span><h3>${esc(b)}</h3></article>`).join('')}</section>${l.videoUrl?`<section class="section video"><iframe src="${esc(l.videoUrl)}" title="Video del proyecto" allowfullscreen></iframe></section>`:''}<section id="galeria" class="section"><span class="kicker">GALERÍA</span><h2>Conoce el entorno</h2><div class="gallery">${(l.gallery||[]).map((img,i)=>`<img src="${esc(img)}" alt="${esc(l.title)} foto ${i+1}" loading="lazy">`).join('')}</div></section><section id="contacto" class="contact"><div><span class="kicker">AGENDA TU VISITA</span><h2>Da el siguiente paso</h2><p>Déjanos tus datos y te contactaremos para resolver dudas y coordinar una visita.</p></div>${l.formEnabled?`<form onsubmit="event.preventDefault();this.innerHTML='<strong>Gracias. Recibimos tu solicitud.</strong><p>Un asesor te contactará pronto.</p>'"><input required placeholder="Nombre"><input required type="tel" placeholder="Teléfono / WhatsApp"><input type="email" placeholder="Correo"><textarea rows="4" placeholder="¿Qué te gustaría saber?"></textarea><button>${esc(l.ctaPrimary||'Solicitar información')}</button></form>`:`<a class="primary" href="${wa}">${esc(l.ctaSecondary||'Hablar por WhatsApp')}</a>`}</section><footer><strong>TU PARCELA LISTA</strong><span>En tu proyecto de campo te acompañamos.</span></footer>`;
})();
