drop function if exists public.registrar_tasacion_mvp(jsonb,jsonb,jsonb,jsonb);
drop table if exists public.revisiones_tasacion;
drop table if exists public.consumos_tasador;
drop table if exists public.tasacion_factores;
drop table if exists public.tasacion_comparables;
drop table if exists public.tasaciones;
drop table if exists public.publicacion_eventos;
drop table if exists public.ventas_declaradas;
drop table if exists public.historial_precios_publicacion;
drop table if exists public.creditos_tasador;
drop table if exists public.suscripciones_comerciales;
drop table if exists public.planes_comerciales;
drop table if exists public.configuracion_tasador;
alter table public.publicaciones drop column if exists consentimiento_uso_ubicacion_en;
alter table public.publicaciones drop column if exists consentimiento_uso_ubicacion;
alter table public.publicaciones drop column if exists precision_ubicacion;
alter table public.publicaciones drop column if exists longitud_publica;
alter table public.publicaciones drop column if exists latitud_publica;
alter table public.publicaciones drop column if exists precio_publico;
alter table public.publicaciones drop column if exists monto_servicio;
alter table public.publicaciones drop column if exists porcentaje_servicio;
alter table public.publicaciones drop column if exists precio_propietario_solicitado;
alter table public.publicaciones drop column if exists tipo_precio_actual;
alter table public.publicaciones drop column if exists usuario_id;
