-- Catálogo público canónico: migra casas y extras legacy a Supabase.
-- Proyecto: qxavbqhyqaqalpzbhwmh

alter table public.casas add column if not exists empresa text;
alter table public.casas add column if not exists tiempo_entrega text;
alter table public.extras add column if not exists empresa text;
alter table public.extras add column if not exists aplica_a text;
alter table public.extras add column if not exists cantidad_default numeric;
alter table public.extras add column if not exists cantidad_minima numeric;
alter table public.extras add column if not exists cantidad_maxima numeric;

insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura18','ChileHome','Casa prefabricada 18m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',18,1,1,2490000,null,'image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp','["image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp","image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp"]'::jsonb,'20 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura24','ChileHome','Casa prefabricada 24m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',24,2,1,3350000,null,'image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto_render.webp','["image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_foto.webp","image/casas/pre_fabricadas/36mts2/pequenas/18_cabana_plano.webp"]'::jsonb,'20 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura36','ChileHome','Casa prefabricada 36m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',36,2,1,4840000,null,'image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto_render.webp','["image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/pequenas/36_caida_agua_plano.webp"]'::jsonb,'20 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura42','ChileHome','Casa prefabricada 42m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',42,3,1,5600000,null,'image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/medianas/42_caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura48','ChileHome','Casa prefabricada 48m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',48,3,1,5950000,null,'image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/medianas/48_caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura54','ChileHome','Casa prefabricada 48m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',54,3,1,6750000,null,'image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_render.webp","image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/medianas/54_6caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura72','ChileHome','Casa prefabricada 72m²','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',72,3,2,8750000,null,'image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp','["image/casas/pre_fabricadas/36mts2/medianas/72_2a_render.webp","image/casas/pre_fabricadas/36mts2/medianas/72_2a_plano.webp"]'::jsonb,'35 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura84_1','ChileHome','Casa prefabricada 82mts2,','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',84,4,2,9200000,null,'image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_plano.webp","image/casas/pre_fabricadas/36mts2/grandes/82_caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura84_2','ChileHome','Casa prefabricada 84mts2 de 6 aguas,','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',84,4,2,9900000,null,'image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/grandes/84_6caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura108','ChileHome','Casa prefabricada 108mts2 de 6 aguas,','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',108,6,2,13500000,'image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp','image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp","image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('aura120','ChileHome','Casa prefabricada 120mts2 de 6 aguas,','Modelo full viene con estructura madera, techumbre,piso forros int y ext, puertas y ventanas.',120,6,2,14700000,'image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp','image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_render.webp','["image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_foto.webp","image/casas/pre_fabricadas/36mts2/grandes/108_6caida_agua_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('Innova18','Innova','Casa Moderna madera full 18mts2,','Valor incluye todo hasta piso ceramico o piso flotante, llegar y habitar.',18,1,1,6300000,'image/casas/pro/innova/innova_1_habitacion_plano.webp','image/casas/pro/innova/innova_1_habitacion_foto.webp','["image/casas/pro/innova/innova_1_habitacion_foto.webp","image/casas/pro/innova/innova_1_habitacion_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('Innova54','Innova','Casa Moderna completa full 54mts2,','Valor incluye todo hasta piso ceramico o piso flotante, llegar y habitar.',54,3,1,12600000,null,'image/casas/pro/innova/innova_3_habitaciones_foto_1.webp','["image/casas/pro/innova/innova_3_habitaciones_foto_1.webp","image/casas/pro/innova/innova_3_habitaciones_foto_2.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.casas (codigo,empresa,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,plano_url,imagen_principal_url,imagenes,tiempo_entrega,activa,actualizado_en) values ('Nogal72','Los Nogales','Casa Moderna completa full 72mts2,','Valor incluye todo hasta piso ceramico o piso flotante, llegar y habitar.',72,3,2,28000000,null,'image/casas/pro/nogales/Alfa_72_mt2_.webp','["image/casas/pro/nogales/Alfa_72_mt2_.webp","image/casas/pro/nogales/Alfa_72_mt2_plano.webp"]'::jsonb,'25 días',true,now()) on conflict (codigo) do update set empresa=excluded.empresa,nombre=excluded.nombre,descripcion=excluded.descripcion,superficie_m2=excluded.superficie_m2,habitaciones=excluded.habitaciones,banos=excluded.banos,precio_base=excluded.precio_base,plano_url=excluded.plano_url,imagen_principal_url=excluded.imagen_principal_url,imagenes=excluded.imagenes,tiempo_entrega=excluded.tiempo_entrega,activa=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('Instalacion_+_base_pilotes_madera','Instalación Pilotes de madera + Casa Full',null,'fundacion','mt2',60000,'nogales',null,1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('Instalacion_+_base_radier','Instalación radier y Casa Full',null,'fundacion','mt2',95000,'nogales',null,1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('Instalacion completa radier + llave en mano full + piso ceramico','Instalacion completa llave en mano full',null,'fundacion','mt2',140000,'nogales',null,1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('Instalacion_electrica','Instalación eléctrica incl/materiales',null,'opcional','mt2',15000,'nogales','casa',1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('piso ceramico','Instalación piso cerámico incl/materiales',null,'opcional','mt2',32000,'nogales','casa',1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('pintura','Servicio pintura con materiales',null,'opcional','mt2',15000,'nogales','casa',1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('instalacion_sanitaria','Instalación sanitaria incl/materiales','Red sanitaria interior referencial según modelo de casa.','opcional','mt2',18000,'nogales','casa',1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('artefactos_cocina','Artefactos cocina','Kit referencial de artefactos de cocina según disponibilidad.','opcional','unidad',850000,null,null,1,1,1,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('artefactos_bano','Artefactos baño','Artefactos sanitarios básicos para baño.','opcional','unidad',750000,null,null,1,1,3,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('fosa_septica','Fosa séptica con instalación precio referencial estimado','Instalación de fosa y kit de drenaje','opcional','unidad',1500000,null,null,1,1,5,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('pozo_profundo','Pozo profundo según profundidad','Excavación de pozo de agua potable','opcional','metro',50000,null,null,30,10,100,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('cierre_perimetral','Cerco de alambre de púas según perímetro de la parcela','Cercado perimetral estimado desde los m² de la parcela seleccionada.','opcional','metro',2000,null,'parcela',100,20,500,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('porton','Portón acceso','Portón de madera/fierro para acceso principal','opcional','unidad',1200000,null,null,1,1,3,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('empalme_electrico','Empalme eléctrico','Acometida y poste para conexión a red eléctrica','opcional','unidad',1500000,null,null,1,1,3,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('maquinaria','Maquinaria retroescavadora','Horas de retroexcavadora/nivelación','opcional','hora',42000,null,null,10,1,100,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('piscina','Piscina','Construcción de piscina de hormigón/fibra','opcional','mt2',200000,null,null,18,6,50,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('quincho','Quincho','Quincho premium de asados techado','opcional','mt2',250000,null,null,12,4,30,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();
insert into public.extras (codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo,actualizado_en) values ('terraza','Terraza','Terraza exterior en madera impregnada','opcional','mt2',200000,null,null,15,5,60,true,now()) on conflict (codigo) do update set nombre=excluded.nombre,descripcion=excluded.descripcion,categoria=excluded.categoria,tipo_calculo=excluded.tipo_calculo,precio_base=excluded.precio_base,empresa=excluded.empresa,aplica_a=excluded.aplica_a,cantidad_default=excluded.cantidad_default,cantidad_minima=excluded.cantidad_minima,cantidad_maxima=excluded.cantidad_maxima,activo=true,actualizado_en=now();

-- Administración de extras desde el mismo CRM.
create or replace function public.crm_listar_extras_admin() returns setof public.extras language plpgsql stable security definer set search_path=pg_catalog as $$ begin perform public.crm_exigir_administrador(); return query select * from public.extras order by categoria,nombre; end; $$;
create or replace function public.crm_guardar_extra_admin(p_extra_id uuid,p_datos jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog as $$ declare v_id uuid; v jsonb; begin perform public.crm_exigir_administrador(); if nullif(trim(p_datos->>'nombre'),'') is null then raise exception using message='CRM_EXTRA_NAME_REQUIRED'; end if; if p_extra_id is null then insert into public.extras(codigo,nombre,descripcion,categoria,tipo_calculo,precio_base,unidad,empresa,aplica_a,cantidad_default,cantidad_minima,cantidad_maxima,activo) values(nullif(trim(p_datos->>'codigo'),''),trim(p_datos->>'nombre'),nullif(trim(p_datos->>'descripcion'),''),coalesce(nullif(trim(p_datos->>'categoria'),''),'opcional'),coalesce(nullif(trim(p_datos->>'tipo_calculo'),''),'unidad'),(p_datos->>'precio_base')::numeric,nullif(trim(p_datos->>'unidad'),''),nullif(trim(p_datos->>'empresa'),''),nullif(trim(p_datos->>'aplica_a'),''),coalesce((p_datos->>'cantidad_default')::numeric,1),coalesce((p_datos->>'cantidad_minima')::numeric,1),coalesce((p_datos->>'cantidad_maxima')::numeric,1),coalesce((p_datos->>'activo')::boolean,true)) returning id into v_id; else update public.extras set codigo=nullif(trim(p_datos->>'codigo'),''),nombre=trim(p_datos->>'nombre'),descripcion=nullif(trim(p_datos->>'descripcion'),''),categoria=coalesce(nullif(trim(p_datos->>'categoria'),''),'opcional'),tipo_calculo=coalesce(nullif(trim(p_datos->>'tipo_calculo'),''),'unidad'),precio_base=(p_datos->>'precio_base')::numeric,unidad=nullif(trim(p_datos->>'unidad'),''),empresa=nullif(trim(p_datos->>'empresa'),''),aplica_a=nullif(trim(p_datos->>'aplica_a'),''),cantidad_default=coalesce((p_datos->>'cantidad_default')::numeric,1),cantidad_minima=coalesce((p_datos->>'cantidad_minima')::numeric,1),cantidad_maxima=coalesce((p_datos->>'cantidad_maxima')::numeric,1),activo=coalesce((p_datos->>'activo')::boolean,true),actualizado_en=now() where id=p_extra_id returning id into v_id; if v_id is null then raise exception using message='CRM_EXTRA_NOT_FOUND'; end if; end if; select to_jsonb(x) into v from public.extras x where id=v_id; return v; end; $$;
revoke all on function public.crm_listar_extras_admin() from public,anon,authenticated; revoke all on function public.crm_guardar_extra_admin(uuid,jsonb) from public,anon,authenticated; grant execute on function public.crm_listar_extras_admin() to authenticated; grant execute on function public.crm_guardar_extra_admin(uuid,jsonb) to authenticated;

create or replace function public.crm_guardar_casa_admin(p_casa_id uuid, p_datos jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog
as $$
declare v_id uuid; v_result jsonb;
begin
  perform public.crm_exigir_administrador();
  if nullif(trim(p_datos->>'nombre'),'') is null then raise exception using message='CRM_HOUSE_NAME_REQUIRED'; end if;
  if p_casa_id is null then
    insert into public.casas(codigo,nombre,descripcion,superficie_m2,habitaciones,banos,precio_base,tipo_construccion,empresa,tiempo_entrega,plano_url,imagen_principal_url,imagenes,activa,destacada)
    values(nullif(trim(p_datos->>'codigo'),''),trim(p_datos->>'nombre'),nullif(trim(p_datos->>'descripcion'),''),(p_datos->>'superficie_m2')::numeric,(p_datos->>'habitaciones')::int,(p_datos->>'banos')::int,(p_datos->>'precio_base')::numeric,nullif(trim(p_datos->>'tipo_construccion'),''),nullif(trim(p_datos->>'empresa'),''),nullif(trim(p_datos->>'tiempo_entrega'),''),nullif(trim(p_datos->>'plano_url'),''),nullif(trim(p_datos->>'imagen_principal_url'),''),coalesce(p_datos->'imagenes','[]'::jsonb),coalesce((p_datos->>'activa')::boolean,true),coalesce((p_datos->>'destacada')::boolean,false)) returning id into v_id;
  else
    update public.casas set codigo=nullif(trim(p_datos->>'codigo'),''),nombre=trim(p_datos->>'nombre'),descripcion=nullif(trim(p_datos->>'descripcion'),''),superficie_m2=(p_datos->>'superficie_m2')::numeric,habitaciones=(p_datos->>'habitaciones')::int,banos=(p_datos->>'banos')::int,precio_base=(p_datos->>'precio_base')::numeric,tipo_construccion=nullif(trim(p_datos->>'tipo_construccion'),''),empresa=nullif(trim(p_datos->>'empresa'),''),tiempo_entrega=nullif(trim(p_datos->>'tiempo_entrega'),''),plano_url=nullif(trim(p_datos->>'plano_url'),''),imagen_principal_url=nullif(trim(p_datos->>'imagen_principal_url'),''),imagenes=coalesce(p_datos->'imagenes','[]'::jsonb),activa=coalesce((p_datos->>'activa')::boolean,true),destacada=coalesce((p_datos->>'destacada')::boolean,false),actualizado_en=now() where id=p_casa_id returning id into v_id;
    if v_id is null then raise exception using message='CRM_HOUSE_NOT_FOUND'; end if;
  end if;
  select to_jsonb(c) into v_result from public.casas c where c.id=v_id;
  return v_result;
end; $$;
revoke all on function public.crm_guardar_casa_admin(uuid,jsonb) from public,anon,authenticated;
grant execute on function public.crm_guardar_casa_admin(uuid,jsonb) to authenticated;
