-- Asesor de Compradores TPL v1
-- Captura consentida, trazabilidad de intereses y continuidad comercial.

alter table public.clientes add column if not exists plazo_compra text;
alter table public.clientes add column if not exists canal_preferido text;
alter table public.clientes add column if not exists frecuencia_contacto text;
alter table public.clientes add column if not exists horario_contacto text;
alter table public.clientes add column if not exists objetivo_compra text;
alter table public.clientes add column if not exists preferencias_busqueda jsonb not null default '{}'::jsonb;
alter table public.clientes add column if not exists asesor_virtual_activo boolean not null default false;
alter table public.clientes add column if not exists journey_id text;

create table if not exists public.cliente_intereses (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references public.clientes(id) on delete cascade,
  tipo text not null default 'parcela',
  propiedad_codigo text,
  origen_propiedad_codigo text,
  accion text not null default 'vista',
  motivo_descarte text,
  metadata jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

create index if not exists cliente_intereses_cliente_fecha_idx
on public.cliente_intereses(cliente_id, creado_en desc);
create index if not exists cliente_intereses_propiedad_idx
on public.cliente_intereses(propiedad_codigo, creado_en desc);

alter table public.cliente_intereses enable row level security;

drop policy if exists "Administradores gestionan intereses" on public.cliente_intereses;
create policy "Administradores gestionan intereses"
on public.cliente_intereses for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.tipo='administrador' and p.activo))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.tipo='administrador' and p.activo));

grant select, insert, update, delete on public.cliente_intereses to authenticated;
grant usage, select on sequence public.cliente_intereses_id_seq to authenticated;

create or replace function public.tpl_captar_comprador_asesor(p_datos jsonb)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_cliente_id uuid;
  v_nombre text := nullif(trim(p_datos->>'nombre'),'');
  v_canal text := lower(nullif(trim(p_datos->>'canal'),'');
  v_correo text := nullif(lower(trim(p_datos->>'correo')),'');
  v_whatsapp text := nullif(regexp_replace(coalesce(p_datos->>'whatsapp',''),'[^0-9+]','','g'),'');
  v_journey text := nullif(trim(p_datos->>'journey_id'),'');
  v_propiedad text;
  v_vista jsonb;
begin
  if coalesce((p_datos->>'acepta_contacto')::boolean,false) is not true then
    raise exception 'Se requiere autorización de contacto';
  end if;
  if v_canal not in ('whatsapp','correo','ambos') then
    raise exception 'Canal inválido';
  end if;
  if v_canal in ('correo','ambos') and (v_correo is null or v_correo !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$') then
    raise exception 'Correo inválido';
  end if;
  if v_canal in ('whatsapp','ambos') and (v_whatsapp is null or length(regexp_replace(v_whatsapp,'[^0-9]','','g')) < 8) then
    raise exception 'WhatsApp inválido';
  end if;

  select id into v_cliente_id
  from public.clientes
  where (v_correo is not null and correo=v_correo)
     or (v_whatsapp is not null and coalesce(whatsapp,telefono)=v_whatsapp)
  order by actualizado_en desc nulls last
  limit 1;

  if v_cliente_id is null then
    insert into public.clientes(
      nombre,correo,telefono,whatsapp,medio_contacto_preferido,canal_preferido,
      plazo_compra,frecuencia_contacto,horario_contacto,objetivo_compra,
      preferencias_busqueda,acepta_tratamiento_datos,asesor_virtual_activo,
      journey_id,estado,etapa,origen,urgencia,ultima_interaccion_en
    ) values (
      coalesce(v_nombre,'Cliente TPL'),v_correo,v_whatsapp,v_whatsapp,v_canal,v_canal,
      nullif(p_datos->>'plazo_compra',''),nullif(p_datos->>'frecuencia',''),
      nullif(p_datos->>'horario',''),nullif(p_datos->>'objetivo',''),
      coalesce(p_datos->'preferencias','{}'::jsonb),true,true,v_journey,
      'nuevo','busqueda_activa','asesor_tpl_web',nullif(p_datos->>'urgencia',''),now()
    ) returning id into v_cliente_id;
  else
    update public.clientes set
      nombre=coalesce(v_nombre,nombre), correo=coalesce(v_correo,correo),
      telefono=coalesce(v_whatsapp,telefono), whatsapp=coalesce(v_whatsapp,whatsapp),
      medio_contacto_preferido=v_canal, canal_preferido=v_canal,
      plazo_compra=coalesce(nullif(p_datos->>'plazo_compra',''),plazo_compra),
      frecuencia_contacto=coalesce(nullif(p_datos->>'frecuencia',''),frecuencia_contacto),
      horario_contacto=coalesce(nullif(p_datos->>'horario',''),horario_contacto),
      objetivo_compra=coalesce(nullif(p_datos->>'objetivo',''),objetivo_compra),
      preferencias_busqueda=preferencias_busqueda || coalesce(p_datos->'preferencias','{}'::jsonb),
      acepta_tratamiento_datos=true, asesor_virtual_activo=true,
      journey_id=coalesce(v_journey,journey_id), estado='activo', etapa='busqueda_activa',
      ultima_interaccion_en=now(), actualizado_en=now()
    where id=v_cliente_id;
  end if;

  for v_vista in select value from jsonb_array_elements(coalesce(p_datos->'parcelas_vistas','[]'::jsonb)) loop
    v_propiedad := nullif(trim(coalesce(v_vista->>'codigo',v_vista#>>'{}')),'');
    if v_propiedad is not null then
      insert into public.cliente_intereses(cliente_id,tipo,propiedad_codigo,accion,metadata)
      values(v_cliente_id,'parcela',v_propiedad,'vista',jsonb_build_object('origen','captacion_asesor_tpl'));
    end if;
  end loop;

  insert into public.cliente_intereses(cliente_id,tipo,accion,motivo_descarte,metadata)
  values(v_cliente_id,'busqueda','solicito_asesor',nullif(p_datos->>'motivo_no_encontro',''),
    jsonb_build_object('plazo_compra',p_datos->>'plazo_compra','canal',v_canal,'journey_id',v_journey));

  return jsonb_build_object('ok',true,'cliente_id',v_cliente_id,'estado','busqueda_activa');
end;
$$;

revoke all on function public.tpl_captar_comprador_asesor(jsonb) from public;
grant execute on function public.tpl_captar_comprador_asesor(jsonb) to anon, authenticated;
